DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 1
    SAMPLER: "RandomSampler"
  TEST:
    BATCH_SIZE: 1
    # SAMPLER: "RandomSampler"
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]
  
# "random_resized_crop": 随机裁剪并调整大小，增加数据的多样性。
# "random_flip": 随机水平翻转，进一步增加数据的多样性。
# "normalize": 标准化图像，使用上面提到的均值和标准差。

OPTIM:
  NAME: "sgd"
  LR: 0.002   # coop 0.0035
  MAX_EPOCH: 20
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 100

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  EFF_PROMPTS:
    N_CTX: 32
    CTX_INIT: ""
    PREC: "fp32"


  COCOOP:
    N_CTX: 4
    CTX_INIT: "a photo of a"
    PREC: "fp16"